# Generated by Django 5.1.2 on 2025-05-04 00:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tether_main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='relationship',
        ),
        migrations.AddField(
            model_name='relationship',
            name='monthly_day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='relationship',
            name='time_of_day',
            field=models.TimeField(default=datetime.time(14, 0)),
        ),
        migrations.AddField(
            model_name='relationship',
            name='weekly_day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='paused',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='Reminder',
        ),
    ]
